pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                // Corrected sed command
                sh '''sed -i 's/<version>3.9.2<\/version>/<version>3.8.7<\/version>/g' pom.xml'''
                // Verify the changes in pom.xml
                sh 'cat pom.xml'
                // Build the project
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
